#! /usr/bin/expect -f
#set timeout -1
spawn yanglint
expect ">"
send "load iana-if-type\r"
expect ">"
send "load ietf-interfaces --feature=ietf-interfaces:\r"
expect ">"
send "load ietf-detnet\r"
expect ">"
#send "data -t data -f json case-a-1.xml\r"
send "data -t data -f json case-a-1.xml -o case-a-1.json\r"
expect ">"
send "data -t data -f xml case-a-1.xml -o case-a-1-out.xml\r"
expect ">"
#send "data -t data -f json case-b-1.xml\r"
send "data -t data -f json case-b-1.xml -o case-b-1.json\r"
expect ">"
#send "data -t data -f json case-b-2.xml\r"
send "data -t data -f json case-b-2.xml -o case-b-2.json\r"
expect ">"
send "data -t data -f json case-c-1-aggregation.xml -o case-c-1-aggregation.json\r"
expect ">"
send "data -t data -f json case-c-1-disaggregation.xml -o case-c-1-disaggregation.json\r"
expect ">"
send "data -t data -f json case-c-2-aggregation.xml -o case-c-2-aggregation.json\r"
expect ">"
send "data -t data -f json case-c-2-disaggregation.xml -o case-c-2-disaggregation.json\r"
expect ">"
send "data -t data -f json case-c-3-aggregation.xml -o case-c-3-aggregation.json\r"
expect ">"
send "data -t data -f json case-c-3-disaggregation.xml -o case-c-3-disaggregation.json\r"
expect ">"
send "data -t data -f json case-c-4-aggregation.xml -o case-c-4-aggregation.json\r"
expect ">"
send "data -t data -f json case-c-4-disaggregation.xml -o case-c-4-disaggregation.json\r"
expect ">"
send "data -t data -f json case-d-1-aggregation.xml -o case-d-1-aggregation.json\r"
expect ">"
send "data -t data -f json case-d-1-disaggregation.xml -o case-d-1-disaggregation.json\r"
expect ">"
send "quit\r"
expect eof
